name: Convert Markdown to HTML

on:
  push:
    paths:
    - "src/**/*.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Install Dependencies
      run: ./scripts/install_dependencies.sh

    - name: Convert Markdown to HTML
      run: ./scripts/md2mindmap.sh

    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        path: docs/
